---
- name: Check space
  hosts: all
  gather_facts: no
  tasks:
    - name: remove stopped dockers
      shell: docker container prune -f
      register: prune

    - debug:
        var: prune
        
    - name: check all dockers
      shell: docker ps -a
      register: all

    - debug:
        var: all.stdout_lines
